name: Go CI/CD

on:
  push:
    branches:
      - main # Run workflow when push to main branch
  pull_request:
    branches:
      - main # Run workflow when pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Thiết lập Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run linter if you have
      - name: Run linter
        run: go vet ./...

      # Run tests
      - name: Run tests
        run: go test ./... -v

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to production
      - name: Deploy
        run: |
          echo "Deploying application..."
          # Thêm lệnh deploy của bạn ở đây
